import Mainnav from "./components/nav/mainnav";
import Navigation from "./components/nav/nav";
import Footer from "./pages/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import { RouterProvider, createBrowserRouter } from "react-router-dom";
import Home from "./page";
import Appletv from "./appletv/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
